"""
Data for creating and operating Sharing Weekend challenges.
"""

STOCK_DAY_NUMBER = 1  # Tuesday
STOCK_NAME = "^AEX"

CHALLENGE_ADMINS = []

QUESTIONS_PATH = "data/weekly_questions.yml"

SUMMARY = ("Each weekend (Sat/Sun/Mon) we look back and find positives "
           "from the past week to celebrate, look forward and set a goal for "
           "the upcoming week, and also have some fun answering questions "
           "that help us get to know each other a little better. "
           )
DESCRIPTION = ("_This Challenge is all about sharing with the party, in the "
               "form of weekly updates: sharing what we have accomplished, "
               "sharing what we need to work on, and sharing miscellaneous "
               "fun things about ourselves (based on a fun question that "
               "changes each week). The challenge also encourages people to "
               "sharing positive content in party chat throughout the week - "
               "things that might inspire a fellow party member, or just make"
               "them smile._"
               "\n\n"
               "**This challenge runs every single week** ***(AND MUST BE "
               "RE-JOINED EVERY WEEK)*** **and includes the following 3 "
               "to-do's, (which must be done on either Saturday, Sunday, or "
               "Monday of the given week):**"
               "\n- Sharing a success (no matter how small! even if it just "
               "getting out of bed!) from the past week with the party so we "
               "can celebrate each others achievements."
               "\n- Thinking about what would be most helpful to work on "
               "during the upcoming week and setting a goal (which we share "
               "with the party) to help us achieve that."
               "\n- Answering a fun get-to-know-you questions. The question "
               "will be different each week."
               "\n\n"
               "**The challenge also includes the following habit (which is "
               "optional to do, and can be done on any day, or every day, or "
               "even multiple times a day). It is meant to encourage people "
               "to share uplifting things in party chat, and reward them with"
               "points/gold/mana when they do:**"
               "\n- Share something positive in party chat (a success, a "
               "quote, a cute or funny picture or link, or anything else "
               "positive)"
               "\n\n"
               "**Every week, one participant who completes all 3 to-do's "
               "will be chosen randomly to be awarded 3 gems** "
               ":gem::gem::gem:: (and will also get this challenge added to "
               "their public list of \"challenges won\")."
               "\n\n"
               "**Please Note: You must officially join the challenge in order"
               "to be eligible to win.**"
               )
