name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install database dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mariadb
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pylint
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Test with pytest
      run: |
        pytest
