name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install database dependencies
      run: |
        sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted"
        sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted"
        sudo apt-get update
        sudo apt-get install mariadb-server-10.3
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pylint
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Test with pytest
      run: |
        pytest
